"use client";
import {useState} from "react";
const products=[
{id:1,name:"Nike Zoom Vomero 5",price:"129 €",tag:"BEST-SELLER",img:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85"},
{id:2,name:"New Balance 9060",price:"119 €",tag:"NEW",img:"https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=900&q=85"},
{id:3,name:"ASICS Gel-Kayano",price:"109 €",tag:"RUNNING",img:"https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=900&q=85"},
{id:4,name:"Nike Air Max",price:"99 €",tag:"LIMITED",img:"https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=900&q=85"}];
export default function Home(){const [active,setActive]=useState("Tous");const [menu,setMenu]=useState(false);const cats=["Tous","Sneakers","Running","Nouveautés"];const filtered=active==="Tous"?products:products.filter(p=>p.tag===active.toUpperCase().replace("NOUVEAUTÉS","NEW")||p.name.toLowerCase().includes(active.toLowerCase().replace("nouveautés","")));return <main>
<header><a className="logo" href="#">RUNNING<span>.6015</span></a><nav><a href="#shop">Shop</a><a href="#about">À propos</a><a href="#faq">FAQ</a></nav><a className="snap" href="https://www.snapchat.com/add/running.6015" target="_blank">Snapchat ↗</a><button className="menu" onClick={()=>setMenu(!menu)}>☰</button></header>
{menu&&<div className="mobileNav"><a href="#shop">Shop</a><a href="#about">À propos</a><a href="#faq">FAQ</a></div>}
<section className="hero"><div className="heroCopy"><p className="eyebrow">DROP 01 — DISPONIBLE MAINTENANT</p><h1>RUN<br/><em>YOUR</em><br/>STYLE.</h1><p className="lead">Des sneakers qui font la différence. Une sélection clean, des prix accessibles et une commande directement sur Snapchat.</p><a className="cta" href="#shop">Découvrir le drop <span>↓</span></a></div><div className="heroVisual"><div className="circle"></div><img src={products[0].img} alt="Sneaker Nike"/></div><div className="heroNote">01 / 04<br/><small>CURATED PAIRS</small></div></section>
<section className="ticker"><span>RUNNING.6015</span><span>QUALITY FIRST</span><span>FAST CONTACT</span><span>SNAP TO ORDER</span></section>
<section id="shop" className="shop"><div className="sectionHead"><div><p className="eyebrow">LA SÉLECTION</p><h2>Le drop <i>du moment.</i></h2></div><div className="filters">{cats.map(c=><button key={c} className={active===c?"active":""} onClick={()=>setActive(c)}>{c}</button>)}</div></div><div className="grid">{filtered.map(p=><article className="card" key={p.id}><div className="photo"><span>{p.tag}</span><img src={p.img} alt={p.name}/><button aria-label="Commander" onClick={()=>window.open("https://www.snapchat.com/add/running.6015","_blank")}>↗</button></div><div className="productInfo"><h3>{p.name}</h3><strong>{p.price}</strong><p>Tailles disponibles · Contact Snapchat pour commander</p></div></article>)}</div></section>
<section id="about" className="manifesto"><p className="eyebrow">POURQUOI 6015 ?</p><h2>Pas besoin d'en faire trop.<br/><i>La paire parle.</i></h2><div className="stats"><div><b>01</b><span>SÉLECTION<br/>CURATÉE</span></div><div><b>02</b><span>PRIX<br/>ACCESSIBLES</span></div><div><b>03</b><span>COMMANDE<br/>VIA SNAP</span></div></div></section>
<section id="faq" className="faq"><p className="eyebrow">FAQ</p><h2>Simple. <i>Rapide.</i></h2><details><summary>Comment commander ? <span>+</span></summary><p>Ajoute running.6015 sur Snapchat et envoie le modèle + ta pointure. On te confirme ensuite la disponibilité et les modalités.</p></details><details><summary>Quelles tailles sont disponibles ? <span>+</span></summary><p>Les tailles varient selon les modèles. Écris-nous sur Snapchat pour connaître les tailles disponibles au moment de ta commande.</p></details><details><summary>Comment vous contacter ? <span>+</span></summary><p>Le moyen le plus rapide est Snapchat : <b>running.6015</b>.</p></details></section>
<footer><div className="logo">RUNNING<span>.6015</span></div><p>© 2026 Running.6015 — All pairs reserved.</p><a href="https://www.snapchat.com/add/running.6015" target="_blank">SNAPCHAT ↗</a></footer>
</main>}
